In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.argmax(a))

4


In [2]:
print(np.argmin(a))

0


In [4]:
a=np.array([10,82,23,7,5])
print(np.argmax(a))

1


In [5]:
print(np.argmin(a))

4


In [6]:
print(np.where(a>3))

(array([0, 1, 2, 3, 4]),)


In [7]:
print(np.cumsum(a))

[ 10  92 115 122 127]


In [8]:
r=np.random.randint(1,20,20)
print(r)

[11  7  9 10 19  6 10  5  8 13  4  2  4 16  5  2 12  8 13 15]


In [9]:
r=np.random.randint(23,30,15)
print(r)

[26 23 28 26 23 23 28 29 25 25 25 28 26 26 26]


In [10]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.corrcoef(a,b))

[[1. 1.]
 [1. 1.]]


In [11]:
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
print(np.corrcoef(a,b))

[[ 1. -1.]
 [-1.  1.]]


In [12]:
a=np.array([1,3,2,1,10,9])
b=np.array([5,10,12,9,3,2])
print(np.corrcoef(a,b))

[[ 1.         -0.74223004]
 [-0.74223004  1.        ]]


In [13]:
a=np.array([1,2,3,4,5])
np.save("ps.npy",a)
print(np.load("ps.npy"))

[1 2 3 4 5]


In [14]:
a=np.array([1,2,3,4,5])
print(a[2:4])

[3 4]


In [15]:
print(a[2:])

[3 4 5]


In [16]:
print(a[:3])

[1 2 3]


In [17]:
print(a[:-3])

[1 2]


In [18]:
print(a[-3:])

[3 4 5]


In [19]:
Arr=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,2]])
print(Arr[0:1,1:3])

[[2 3]]


In [20]:
print(Arr[:,1:2])

[[2]
 [4]
 [8]]


In [21]:
print(Arr[:,::2])

[[1 3]
 [3 5]
 [7 9]]


In [23]:
print(Arr[:,::])

[[1 2 3 4]
 [3 4 5 6]
 [7 8 9 2]]
