In [1]:
a=10
a

10

In [2]:
a=10
b=20
a
b

20

In [3]:
a=[22,33,44,55]
a

[22, 33, 44, 55]

In [4]:
import numpy as np
score=np.array(a)
score

array([22, 33, 44, 55])

In [5]:
d=np.mean(score)
d

np.float64(38.5)

In [6]:
print(np.max(score))

55


In [7]:
print(np.min(score))

22


In [8]:
f=np.zeros([3,4])
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
f=np.ones([5,5])
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
g=np.random.rand(5,4)

g

array([[0.52859904, 0.8208915 , 0.59350741, 0.50557988],
       [0.03534825, 0.44301184, 0.69827411, 0.28558102],
       [0.30963904, 0.05881481, 0.8908634 , 0.59034798],
       [0.6523728 , 0.78115621, 0.97058257, 0.28028563],
       [0.44804716, 0.83873662, 0.57028784, 0.84103481]])

In [11]:
a=np.array([11,22,33,4,5,6,7,8,9,2,4,6,1,22,3,4])
d=np.reshape(a,(2,8))
d

array([[11, 22, 33,  4,  5,  6,  7,  8],
       [ 9,  2,  4,  6,  1, 22,  3,  4]])

In [12]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
c=np.array([11,22,33,4,5,6,7,8,9,2,4,6,1,22,3,4])
d=c[3:6]
d

array([4, 5, 6])

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a-b

array([-3, -3, -3])

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [3]:
import numpy as np
a = np.array([[1,2,3],[6,7,8]])
b = np.array([[4,5],
              [8,4],
              [6,5]])
c=np.dot(a,b)
c

array([[ 38,  28],
       [128,  98]])

In [4]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
arr = np.array([5,2,8,1,9])
print(np.sort(arr))

[1 2 5 8 9]


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [7]:
arr = np.array([1,2,2,3,4,4,5])
d=np.unique(arr)
d

array([1, 2, 3, 4, 5])

In [8]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
arr = np.linspace(1,10,5)
print(arr)


[ 1.    3.25  5.5   7.75 10.  ]
